config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  get "/pages" => "pages#index"

  resources :movies
  get "/liked" => "movies#liked" 
  post '/movie/:id/like', to: 'movies#like', as: 'like'
  delete "/liked/:id" => "movies#unlike"

  get "/users" => "users#index"
  get "/users/:id" => "users#show"
  get "/signup" => "users#new"
  post "/users" => "users#create"

  get "/login" => "sessions#new"
  post "/sessions" => "sessions#create"
  get "/logout" => "sessions#destroy"

  put 'users/:id/friend', to: 'users#friend', as: 'friend'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friendship.rb
class Friendship < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  validates :user_id, uniqueness: {scope: :movie_id}
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :likes
  has_many :users, through: :likes
  def liked?(user)
    !!self.likes.find{|like| like.user_id == user.id}
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  has_many :likes
  has_many :movies, through: :likes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
 
  def authenticate_user
    redirect_to '/login', status: :see_other unless current_user
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all 
  end

  def show
    @movie = Movie.find_by(id: params[:id])
  end

  def like 
    @movie = Movie.find_by(id: params[:id])
    Like.create(user_id: current_user.id, movie_id: @movie.id)
    redirect_to "/movies/#{@movie.id}"
  end

  def unlike
    @like = Like.where(user_id: current_user.id, movie_id: @movie.id)
  end

  def liked
    @movies = current_user.movies
    render :liked
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render template: "sessions/new"
  end
 
  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to "/"
    else
      redirect_to "/login"
    end
  end
 
  def destroy
    session[:user_id] = nil
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all 
  end

  def show 
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
    render template: "users/new"
  end

  def create
    @user = User.new(
      name: params[:user][:name],
      email: params[:user][:email],
      password: params[:user][:password],
      password_confirmation: params[:user][:password_confirmation],
    )
    if @user.save
      session[:user_id] = @user.id
      redirect_to "/"
    else
      render :new, status: :unprocessable_entity
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie Night</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="page-container">
      <div id="content-wrap">
        <% @rand_movie = Movie.all.sample %>

        <nav class="navbar navbar-expand-lg bg-body-tertiary">
          <div class="container-fluid">
            <a class="navbar-brand" href="/">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <% if current_user %>
                  <a class="nav-link active" aria-current="page" href="/liked">My Movies</a>
                <% end %>
                <a class="nav-link active" href="/movies/<%= @rand_movie.id %>">Random Movie</a>
                <% if current_user %>
                  <a class="nav-link active" href="/logout">Log Out</a>
                <% else %>
                  <a class="nav-link active" href="/login">Log In</a>
                <% end %>
              </div>
            </div>
          </div>
        </nav>
        <br>
        <%= yield %>
      </div>
      <footer id="footer">
      <p>Buy this site for $19.99</p>
      </footer>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

app/views/movies/index.html.erb
<h1>All Movies</h1>
<% @movies.each do |movie| %>
  <h2><%= movie.title %></h2>
  <p><%= movie.genre %></p>
  <p>Rating: <%= movie.rating %>%</p>
  <p><%= movie.plot %></p>
<% end %>

app/views/movies/liked.html.erb
<h1><%= current_user.name %>'s Movies</h1>
<% @movies.each do |movie| %>
  <% input = movie.title.gsub(" ","+") %>
  <% response = HTTP.get("https://www.omdbapi.com/?t=#{input}&apikey=d5600087") %>
  <% movie_response = response.parse(:json) %>
  <div class="liked_movies">
  <a class="mymovies" href="/movies/<%= movie.id%>"><%= movie.title %></a>
  <br>
  <a href="/movies/<%= movie.id %>"><img src="<%= movie_response["Poster"] %>"></a>
  </div>
  <br>
  <br>
<% end %>

app/views/movies/show.html.erb
<% input = @movie.title.gsub(" ","+") %>
<% response = HTTP.get("https://www.omdbapi.com/?t=#{input}&apikey=d5600087") %>
<% movie_response = response.parse(:json) %>
<% image = movie_response['Poster'] %>

<h1><%= @movie.title %></h1>
<img src="<%= image %>" width="300" height="450">
<p>Rating: <%= movie_response['Rated'] %></p>
<p>Director: <%= movie_response['Director'] %></p>
<p>Cast: <%= movie_response['Actors'] %></p>
<p>Genre(s): <%= @movie.genre %></p>
<% if movie_response['Ratings'] %>
<% movie_response['Ratings'].each do |rating| %>
  <% if rating['Source'] == "Rotten Tomatoes" %>
    <p>Rotten Tomatoes: <%= rating['Value'] %>
    <% if rating['Value'].to_i > 60 %>
      <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Rotten_Tomatoes.svg/757px-Rotten_Tomatoes.svg.png" width="20" height="20">
    <% else %>
      <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Rotten_Tomatoes_rotten.svg/1200px-Rotten_Tomatoes_rotten.svg.png" width="20" height="20">
    <% end %>
    </p>
  <% end %>
<% end %>
<% end %>
<p>Plot: <%= movie_response['Plot'] %></p>

<% if current_user %>
  <% if Like.where(user_id: current_user.id, movie_id: @movie.id).exists? %>
    <button type="button">Liked</button>
  <% else %>
    <%= button_to "Like", like_path(@movie), method: "post" %>
  <% end %>
<% end %>

app/views/pages/index.html.erb
<% date = Time.new %>
<% tonights_movies = Movie.where(scheduled_on: date.yday) %>

<% if current_user %>
  <% my_movies = current_user.movies.sample(3) %>
<% end %>

<h1 class="siteTitle">Movie Night</h1>

<% tonights_movies_array = Array.new %>
<% tonights_id_array = Array.new %>
<h3>Tonight's Movies</h3>
<% tonights_movies.each do |movie| %>
    <% tonights_id_array << movie.id %>
    <% input = movie.title.gsub(" ","+") %>
    <% response = HTTP.get("https://www.omdbapi.com/?t=#{input}&apikey=d5600087") %>
    <% movie_response = response.parse(:json) %>
    <% tonights_movies_array << movie_response %>
  <% end %>
<div id="carouselExampleAutoplayingone" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <a href="/movies/<%= tonights_id_array[0] %>"><img src="<%= tonights_movies_array[0]['Poster'] %>" class="d-block w-100" alt="..." height="450"></a>
    </div>
    <div class="carousel-item">
      <a href="/movies/<%= tonights_id_array[1] %>"><img src="<%= tonights_movies_array[1]['Poster'] %>" class="d-block w-100" alt="..." height="450"></a>
    </div>
    <div class="carousel-item">
      <a href="/movies/<%= tonights_id_array[2] %>"><img src="<%= tonights_movies_array[2]['Poster'] %>" class="d-block w-100" alt="..." height="450"></a>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplayingone" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplayingone" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<br>

<% my_movies_image_array = Array.new %>
<% my_movies_id_array = Array.new %>
<% if current_user %>
<h3><a class="mymovies" href="/liked"><%= current_user.name %>'s Movies</a></h3>
<% my_movies.each do |movie| %>
    <% my_movies_id_array << movie.id %>
    <% input = movie.title.gsub(" ","+") %>
    <% response = HTTP.get("https://www.omdbapi.com/?t=#{input}&apikey=d5600087") %>
    <% movie_response = response.parse(:json) %>
    <% my_movies_image_array << movie_response %>
  <% end %>

  <div id="carouselExampleAutoplayingtwo" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <a href="/movies/<%= my_movies_id_array[0] %>"><img src="<%= my_movies_image_array[0]['Poster'] %>" class="d-block w-100" alt="..." height="450"></a>
      </div>
      <div class="carousel-item">
        <a href="/movies/<%= my_movies_id_array[1] %>"><img src="<%= my_movies_image_array[1]['Poster'] %>" class="d-block w-100" alt="..." height="450"></a>
      </div>
      <div class="carousel-item">
        <a href="/movies/<%= my_movies_id_array[2] %>"><img src="<%= my_movies_image_array[2]['Poster'] %>" class="d-block w-100" alt="..." height="450"></a>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplayingtwo" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplayingtwo" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <br>

<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>
<% @users.each do |user| %>
  <h2><%= user.name %></h2>
<% end %>

app/views/users/new.html.erb
<h1>Signup</h1>
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <% @user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
    <% @user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
    <% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/show.html.erb
<% movies = @user.movies %>
<h1><%= @user.name %></h1>
<h2><%= @user.name %>'s Liked Movies</h2>
<% movies.each do |movie| %>
  <% input = movie.title.gsub(" ","+") %>
  <% response = HTTP.get("https://www.omdbapi.com/?t=#{input}&apikey=d5600087") %>
  <% movie_response = response.parse(:json) %>
  <a href="/movies/<%= movie.id%>"><%= movie.title %></a>
  <img src="<%= movie_response["Poster"] %>"> 
  <br>
<% end %>